### DISCUSSION TITLE
Error: Cannot find module '@faceless-ui/slider' on Docker

### DISCUSSION THREAD

**Discussion by mumincelal** [faceless-ui/slider#20] [Q&A]
I am running PayloadCMS-NextJS app on Docker. But when I try to open webpage, getting below error.

```
Error: Cannot find module '@faceless-ui/slider'
Require stack:
- /app/.next/server/pages/_app.js
- /app/node_modules/next/dist/server/require.js
- /app/node_modules/next/dist/build/index.js
- /app/dist/src/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at /app/node_modules/next/dist/server/require-hook.js:108:36
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at 1091 (/app/.next/server/pages/_app.js:165:18)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
    at /app/.next/server/chunks/328.js:2831:77
    at __webpack_require__.a (/app/.next/server/webpack-runtime.js:89:13)
    at 8244 (/app/.next/server/chunks/328.js:2822:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/.next/server/pages/_app.js',
    '/app/node_modules/next/dist/server/require.js',
    '/app/node_modules/next/dist/build/index.js',
    '/app/dist/src/server.js'
  ]
}
```

My Dockerfile:

```
# [BASE] LAYER
FROM node:19-alpine AS base

WORKDIR /app

COPY package*.json yarn.lock* ./
COPY .yarn ./.yarn
COPY .yarnrc.yml ./

RUN yarn install

# [BUILD] LAYER
FROM base AS build

WORKDIR /app

COPY . .

RUN yarn build

# [PRODUCTION] LAYER
FROM node:19-alpine AS production

WORKDIR /app

COPY --from=build /app .

# COPY package*.json yarn.lock* ./
# COPY .yarn ./.yarn
# COPY .yarnrc.yml ./

# RUN yarn workspaces focus --all --production

# COPY --from=build /app/dist ./dist
# COPY --from=build /app/build ./build
# COPY --from=build /app/public ./public
# COPY --from=build /app/.next ./.next

EXPOSE 3000

CMD ["node", "dist/src/server.js"]
```

My Docker Compose file:

```
version: '3.3'

services:
  payload:
    container_name: payload
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
    networks:
      - payload-network
    working_dir: /app
    restart: always
    depends_on:
      - mongo
      - meilisearch
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    networks:
      - payload-network

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    networks:
      - payload-network

volumes:
  data:
  node_modules:

networks:
  payload-network:

```

I didn't understand where the problem is this.

Could you help me to solve this?
